### ISSUE TITLE
Installation/Set Up Instructions

### ISSUE THREAD

**Issue by galenandrew** [robertdolca/dotfiles-manager#2]
Love what this project does, but am a little confused on installation. To get this set up do I clone the repo into my home directory `~/` or `/usr/local/bin`, etc? Any other dependencies to run?

Thanks!

**Comment by benjaminparnell** [comment]
@galenandrew I cloned into `~/dotfiles` and run with `~/dotfiles/dotfiles collect -v`. It will store files in a folder called `files` like so `path/to/script/files`, so in my case `~/dotfiles/files`. I ended up changing the script to put files straight in `~/dotfiles` (where the script is), and then removed the git remote and added a new one for my own dotfiles repo and pushed. 

There aren't any other dependencies to run, just standard tools like `sed` and `cat`.

**Comment by galenandrew** [comment]
:metal: thanks for the info @benjaminparnell!!
